name: NodeJS with Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build
        run: |
          npm install
          npm run build
      - uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist/
  build-android:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
      - name: install
        run: |
          npm install

      - uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist/
      - name: sync
        run: |
          npx cap sync
          npx cap copy
          cd android
      - name: buid-android
        run: |
          chmod +x ./gradlew
          ./gradlew app:assemble
      - uses: actions/upload-artifact@v3
        with:
          name: apks
          path: app/build/outputs/apk/release/*
